name: Test E2E

on:
  push:
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      php:
        image: php:8.1-cli
        options: >-
          --health-cmd "php -v"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start PHP server
      run: php -S localhost:8000 -t public &
      shell: bash

    - name: Run TestCafe
      run: npx testcafe chrome tests/nom.test.js
